### ISSUE TITLE
Follow-up

### ISSUE THREAD

**Issue by dwrz** [nagamocha3000/db-logger-golang#1]
I've been experimenting with the new `slog` package. I'm not super happy with it, and still am not sure how I feel about structured logging in general, which led to me exploring some ideas, including something like the approach you discuss here. Do you have any follow-up on the approach you've tried here? Have you tried anything like this in a production environment?

**Comment by bnmoch3** [comment]
Hmm, I wrote this a while back when I was a junior dev, new to databases, new to Go, and mostly using the language for toy projects so on revisiting it I definitely see some issues. To answer your main question, both back then and even now I've never used this method on production and I wouldn't recommend it.  

Unstructured logging is decent for CLI tools and single-node apps where you'll mostly be grokking through the logs using unix CLI tools (grep, sed etc).  

For everything else structured logging is worth the extra effort. For example, in this demo, I was using regex parsing to derive structure from the log entry so why not just use structured logging from the get-go.  

Also structured logging libraries have come a long way. Both zerolog and zap are quite lightweight and support pretty-printing, back then I was only familiar with logrus.

**Comment by dwrz** [comment]
Thanks for the insights!

**Comment by bnmoch3** [comment]
You're welcome
